composer/xdebug-handler

.gitignore
LICENSE
README.md
composer.json
phpunit.xml.dist
src/XdebugHandler.php
tests/XdebugHandlerMock.php
tests/XdebugHandlerTest.php
tests/XdebugIniTest.php

The main items that needed to be changed were the dependencies on `Symfony\Component\Console\Output` and `Composer\Utils\IniHelper`.
The former has been replaced by `hasColorOutput()` (which was actually in the early XdebugHandler versions) and the latter with a new static function `getAllIniFiles()`.

Minimal changes to decouple from composer

---

src/XdebugHandler.php

I have no idea why running the tests locally did not catch this.

Fix undefined constant

---

src/XdebugHandler.php
tests/XdebugHandlerMock.php
tests/XdebugHandlerTest.php

COMPOSER_XDEBUG_VERSION was used internally by Composer to add xdebug to
the PlatformRepository when it had been restarted without it. In the
interests of limiting the number of environment variables being used,
Composer can now get this information from a new static method:
XdebugHandler::getSkippedVersion()

Remove internal environment variable

---

src/XdebugHandler.php
tests/XdebugColoursTest.php

There are other common color options to the `--ansi` and `--no-ansi`
used by Composer. This PR enables the use of `--xxxx`, `--no-xxxx` and
`--xxxx=xxx` formats by introducing an optional constructor param.

Allow common command-line color options

---

src/XdebugHandler.php

Consistently using the correct new function name would have been a good
start, but in addition the logic was flawed for Windows.
Cygwin and Msys (and therefore Git Bash), emulate pseudo terminals by
using named pipes, so `sapi_windows_vt100_support` and any test for a
tty will fail. However, this is not the case when Git Bash is given the
name of a program to run that requires a PATH lookup, rather than being
given the full filename.
As such, we should only rely on the specific environment variables.

Fix flaws in detecting color support

---

src/XdebugHandler.php
tests/MainTest.php

The original logic was too clever for its own good and led to a bug in
the code to restore the variable. This simplifies things by including a
'scannedInis' flag in the restart environment variable.

Simplify PHP_INI_SCAN_DIR logic and fix bug

---

src/XdebugHandler.php
tests/RestartTest.php

Code that is executed directly (from stdin, --run or interactively)
cannot be used in a restarted process.
Thanks to Bruce Weirdan https://github.com/weirdan

Prevent restart with directly executed code

---

src/Status.php
src/XdebugHandler.php
tests/RestartTest.php

If XdebugHandler is auto-prepended, stdin can be read by the restarted
process. If this is not the case, then the restarted process will have
nothing to execute and will exit immediately if it is not interactive.
Status messages have been added to show if directly executed code is
being used and to report when the restarted process exits. Additionally
the constant STDOUT is checked before use, as it is not defined when
code is provided via stdin.
Thanks again to Bruce Weirdan https://github.com/weirdan

Now allow a restart with all directly executed code

---

src/Process.php
src/Status.php
src/XdebugHandler.php
tests/EnvironmentTest.php
tests/Helpers/BaseTestCase.php
tests/Mocks/CoreMock.php

It is important that the $_SERVER environment reflects the changes made
when restoring the restart variables. Otherwise a subprocess created
with $_SERVER as its environment will receive restart specific values.
This will break configuration if scanned inis are being used.

Update $_SERVER environment in restarted process

---

CHANGELOG.md
README.md
src/XdebugHandler.php
tests/EnvironmentTest.php
tests/Helpers/BaseTestCase.php
tests/Mocks/CoreMock.php
tests/SettingsTest.php

Calling a PHP process from a restarted process is no different from calling it normally, except that xdebug will be loaded in that process. Of course if the process implements xdebug-handler, that process will also be restarted.
This PR stores settings in the environment after a restart, and provides a method to retrieve them.
```php
$settings = XdebugHandler::getRestartSettings();
/**
* $settings: array (if the current process was restarted,
* or called with the settings from an existing restart), or null
*
*    'tmpIni'      => the temporary ini file used in the restart (string)
*    'scannedInis' => if there were any scanned inis (bool)
*    'scanDir'     => the original PHP_INI_SCAN_DIR value (false|string)
*    'inis'        => the original inis from getAllIniFiles (array)
* …
```

Store restart settings for use in sub-processes

---

src/XdebugHandler.php

When we did some tests in Infection we found that the xdebug-handler has dependency on the `ctype` extension and some of our users may not have this extension.
So this PR does this extension optional. IniFilesTest covers this case.
Reference: https://github.com/infection/infection/pull/263#issuecomment-381012052

Make ctype extension optional

---

src/XdebugHandler.php
tests/IniFilesTest.php

@weirdan Following on from your comments on https://github.com/composer/xdebug-handler/pull/61 (apologies, I didn't see it until after I had merged it), I've used `addcslashes` to escape backslashes and double-quotes when transforming the ini value into a double-quoted entry in the ini file.

Make ini value escaping more robust

---

CHANGELOG.md
README.md
src/XdebugHandler.php
tests/EnvironmentTest.php
tests/Helpers/BaseTestCase.php
tests/Helpers/EnvHelper.php
tests/Helpers/IniHelper.php
tests/RestartTest.php
tests/SettingsTest.php

When specifying an ini file on the command-line, there are two ways to
stop PHP scanning for additional ini files - either by setting
`PHP_INI_SCAN_DIR` to an empty string or using the `-n` option. Neither
are documented as doing this in the PHP manual.
xdebug-handler always used the first method (and restored the
environment in the restart). Later, after debugging through the PHP
source code, it became apparent that another solution was to use `-n`,
but there seemed little point in changing something that was already
working at that time.
Note that `main/php_ini.c` is quite explicit about this usage, with the
following code comment, from August 2008:
If SAPI does not want to ignore all ini files OR an overriding
file/path is given. This allows disabling scanning for ini files in
the …

Use command-line option to suppress ini scanning

---

README.md
src/PhpConfig.php
tests/EnvironmentTest.php
tests/Mocks/CoreMock.php
tests/PhpConfigTest.php

I originally thought that this should not be part of the main library, but it is a tiny class (it doesn't add much more than recently removed scan-dir code) which also makes it easier to explain the various sub-process strategies.

Add helper class to manage PHP sub-processes

---

README.md
src/Process.php
tests/ColourOptionTest.php

We faced an issue when we tried to add colour option for command that is using double dash,
eg adding `--ansi` for `php-cs-fixer fix -v -- fileA.php fileB.php`
With current state, `--ansi` ends always as last place, thus after `--`, which won't work and:
- command won't be run with enforcing colour output
- command will get `--ansi` as position argument (and not option) and fail to handle it
More details at https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3901

Process::addColorOption when double dash is one of args

---

README.md
src/Process.php
tests/ColourOptionTest.php

When the main script was removed from the array of arguments passed to
addColorOption, the searching logic was not updated to reflect
that zero might be returned as an array index.

Fix regression in Process::addColorOption

---

src/XdebugHandler.php

When the current ini settings are merged into the ini file content, a
setting will be added if it exists but doesn't match the current value.
In the case of apc.mmap_file_mask, the value is a template string that
is used by the system `mkstemp`, which PHP unfortunately updates to the
actual file being used. If this is added to the tmp ini, it causes
`mkstemp` to fail and a fatal error.

Fix apc.mmap_file_mask being updated in tmp ini

---

src/XdebugHandler.php
tests/EnvironmentTest.php
tests/Helpers/EnvHelper.php
tests/PhpConfigTest.php
tests/SettingsTest.php

If the PHP build does not set a --with-config-file-scan-dir value (on
Windows mainly), `php_ini_scanned_files` always fails. This is now
fixed in 7.1.13 and 7.2.1. See https://bugs.php.net/73124
When xdebug-handler used the environment to suppress ini-scanning, this
did not matter - although xdebug may not have been disabled. But now
that command-line options are used, configuration from the scanned inis
will not be used in the restart.
This fix ensures that the restart fails in such a situation, with an
appropriate status message.

Check that php_ini_scanned_files() is functional

---

src/XdebugHandler.php
tests/Helpers/IniHelper.php
tests/IniFilesTest.php

If an ini file is not readable (file permissions, open_basedir setting,
system lock etc) then PHP would show a warning and xdebug-handler would
carry on regardless. In retrospect this strategy seems flawed because
the restarted process will not receive all its intended settings.
This PR changes this behaviour by disabling PHP error output and simply
not restarting. Error output is also disabled when calling tempnam.
Prompted by https://github.com/composer/composer/issues/7807

Do not restart if an ini file is inaccessible

---

src/Process.php

Update `$_ENV` if it was populated to reflect environment changes. Say, Symfony's Process will happily import anything from `$_ENV`, but if we only update the global environment (remove some variables), it'll have no effect on `$_ENV` if it was populated before. Which happens when `variables_order` contains an `E`.
Please let me know if this makes any sense.

Update $_ENV if it was populated

---

src/XdebugHandler.php

Make sure `uopz` isn't disabled in ini, prevents fatals like:
```
Fatal error: Uncaught RuntimeException: uopz is disabled by configuration (uopz.disable) in ...
```
Ref: https://github.com/krakjoe/uopz/blob/a45fcaa5177ece9c2d83d79086f089b7f1c9d3dd/uopz.c#L45
Thank you!

XdebugHandler: check if uopz isn't disabled in ini

---

README.md
composer.json
src/Status.php
src/XdebugHandler.php
tests/IniFilesTest.php
tests/Mocks/CoreMock.php
tests/Mocks/FailMock.php

This PR
💁‍♂ For reference, also see 
- https://twitter.com/derickr/status/1184465999971700736
- https://github.com/composer/composer/pull/8406

Fix: Xdebug vs xdebug

---

.travis.yml
appveyor.yml
composer.json
phpunit.xml.dist

Tested on phpunit 6 and 7. Not compatible with phpunit 8 because it
requires return type declarations for extended classes.

Updates for PHP and phpunit

---

src/Process.php
tests/ColourOptionTest.php

This overrides adding the `colorOption` argument to the restart command
line if the NO_COLOR environment variable exists and no specific color
argument has been provided. See: https://no-color.org/

Add support for NO_COLOR environment variable

---

src/XdebugHandler.php
tests/Helpers/IniHelper.php

When `XdebugHandler` comes across an empty ini file, it report a `Unable to read ini` error. This appears to be caused by loose type matching when calling [`file_get_contents`](https://www.php.net/manual/en/function.file-get-contents.php#refsect1-function.file-get-contents-returnvalues).
The result of this error, in particular, causes `composer` to not restart itself with `xdebug` disabled.

Fix empty ini handling

---

src/XdebugHandler.php

Ran into this while trying to implement https://github.com/composer/composer/commit/a07f9ffba98fe5472a3004b56299ca99e22dc6c9 and going insane wondering why the signal handler was never called :) This commit fixes it.

Ignore SIGINTs to let the restarted process handle them

---

README.md
src/XdebugHandler.php

Restores the `SIGINT` handler (if it has not been set) in the restarted process. Fixes https://github.com/composer/xdebug-handler/issues/109

Fix signal handling in the restarted process

---

src/XdebugHandler.php

If function `pcntl_signal()` is disabled following exception is thrown when running `xdebug-handler`:  
`PHP Fatal error:  Uncaught ErrorException: pcntl_signal() has been disabled for security reasons`
This PR fixes the issue.

Fix Exception if 'pcntl_signal' is disabled

---

src/XdebugHandler.php

Since f748184f / 2a7c843 proc_open() if available is preferred over
passthru().
The configuration check would not recognize it thought. Minor. I think we
forget it back in November.
Ref: f748184fed8dce2a3d4f16bed2859bac0f506799
Ref: 2a7c84364bb48f4611af1f068333b4d1bbb47807

Proc_open fall-back for passthru config check

---

README.md
src/XdebugHandler.php

Windows console event handling can be problematic because CTRL+C signals
may be disabled and this is inherited by child processes. Also there is
no `pcntl_signal_get_handler` equivalent in Windows PHP, so it is
impossible to know if signals are enabled or if a handler has been
registered.
When creating a handler, `sapi_windows_set_ctrl_handler` automatically
enables CTRL+C signals in the current process (and by default any child
process). In order to enable and transfer CTRL handling to the restarted
process, we register a handler in the parent that doesn't do anything
resulting in any existing handler being overwritten and the suppression
of CTRL events.

Add Windows CTRL event handling on PHP 7.4+

---

README.md
src/XdebugHandler.php
tests/Mocks/CoreMock.php
tests/Mocks/FailMock.php
tests/Mocks/PartialMock.php
tests/RestartTest.php

In PHP-7.4 `proc_open` accepts an array of command-line options which are automatically quoted for the OS. This enables the shell to be bypassed and the php process to be called directly for the restart.
This feature is used if available, otherwise the command-line is quoted as before. Support for `passthru` has been dropped to make life simpler.
Note: This requires a version bump to 2.0

Bypass shell when restarting in PHP 7.4+

---

README.md
src/XdebugHandler.php
tests/ClassTest.php
tests/Mocks/CoreMock.php
tests/Mocks/FailMock.php
tests/Mocks/PartialMock.php

Removes `array` typehint on protected `restart` method. This gives us the option to increase the minimum PHP for version 2 and not cause any pain for apps that extend this method and support older versions (in all dependents listed on Packagist they use this method to modify the tmp ini file, rather than modify the command).

Don't typehint restart for 1.x compatibility

---

README.md
src/Status.php
src/XdebugHandler.php
tests/ClassTest.php
tests/Mocks/CoreMock.php
tests/RestartTest.php

Xdebug3 introduces specific modes and mode `off` adds minimal overhead to the process. Mode discovery is best-attempt and will be solved when Xdebug provides a specific function.
A static helper function `isXdebugOff()` is provided to determine if Xdebug is loaded and running with xdebug.mode=off.

Do not restart if xdebug mode is off

---

src/PhpConfig.php
src/Process.php
src/XdebugHandler.php
tests/IniFilesTest.php

Removes @internal annotation to make utility methods safely available. They are already being copied or used by some implementations.

Open up Process class

---

composer.json
phpstan.neon.dist
tests/bootstrap_phpstan.php

PHPStan cannot find PHPUnit classes when simple-phpunit is being used because they are not in the autoloader. This fix ensures that PHPUnit is installed in `vendor/bin/.phpunit` and autoloads the classes. 
It uses the `vendor/bin/.phpunit/phpunit` directory that simple-phpunit creates with a symlink from the installed phpunit folder. However this won't work on Windows, where you (generally) need to be an admin to create symlinks: https://github.com/symfony/symfony/pull/40754

Fix phpstan when using simple-phpunit

---

.github/workflows/continuous-integration.yml
src/XdebugHandler.php

cmd.exe does not support a UNC path as the working directory and will change it to the Windows directory before executing any command. We bypass cmd.exe on PHP 7.4+ by calling the php binary directly so this only affects earlier versions.
See: https://github.com/composer/composer/issues/9858

Do not restart with cmd.exe if cwd is a UNC path

---

src/XdebugHandler.php

As per: https://github.com/xdebug/xdebug/commit/c6ebf3105eb287231bb9d0b913951c1017958f1f
Xdebug 3.1 scheduled release date: 2021-06-30

Use xdebug_info to get mode in Xdebug-3.1

---

phpstan.neon.dist
src/XdebugHandler.php

Note that the removal of the version check (>= 5.3.6) for `DEBUG_BACKTRACE_IGNORE_ARGS` is safe, because we have already bailed on PHP < 5.4.

Updates for phpstan level 7

---

composer.json
phpstan.neon.dist
src/Process.php
src/XdebugHandler.php
tests/IniFilesTest.php
tests/RestartTest.php

Above level 7 phpstan gives us:
```
------ -----------------------------------------------------------------------------------------------
Line   src\Process.php
------ -----------------------------------------------------------------------------------------------
44     Parameter #2 $subject of function preg_match expects string, string|null given.
47     Parameter #1 $string of function strpbrk expects string, string|null given.
54     Parameter #3 $subject of function preg_replace expects array|string, string|null given.
58     Parameter #3 $subject of function preg_replace expects array|string, string|null given.
61     Method Composer\XdebugHandler\Process::escape() should return string but returns string|null.
------ ------------------------------------------------------------------- …
```

Updates for phpstan level 9

---

src/XdebugHandler.php
tests/Helpers/BaseTestCase.php
tests/Mocks/CoreMock.php
tests/SettingsTest.php

Reported here  https://github.com/composer/composer/pull/10416

Fix isXdebugActive if used before class instantiation

---

tests/IniFilesTest.php
tests/SettingsTest.php

Hi,
Without this typo fix, latest versions of phpunit error out with a code 2.
phpunit
PHPUnit 10.1.3 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.2.5
Configuration: /build/php-composer-xdebug-handler-3.0.3/phpunit.xml.dist
...................................................               51 / 51 (100%)
Time: 00:00.076, Memory: 8.00 MB
There were 2 PHPUnit errors:
1) Composer\XdebugHandler\Tests\IniFilesTest::testIniSections
The data provider specified for Composer\XdebugHandler\Tests\IniFilesTest::testIniSections is invalid
Method Composer\XdebugHandler\Tests\IniFilesTest::iniSectionsProvider      *() does not exist
/build/php-composer-xdebug-handler-3.0.3/tests/IniFilesTest.php:163
2) Composer\XdebugHandler\Tests\SettingsTest::testGetRestartSettings
The data provider …

Adapt to recent version of PHPUnit (10)

---

README.md
tests/App/README.md

This relates to commit 5b92607 (which I forgot to PR) that introduces functional testing.
This comprises a series of scripts that output formatted data from the internal logger and the script itself, which can then be tested.
Additionally, these scripts can be run on the command-line with an additional option that colorizes the output and provides more information.

Document using functional test scripts
